### ISSUE TITLE
Project Launch

### ISSUE THREAD

**Issue by TawhidGias** [ashik5757/ScoreBoard-Project#7]
When I have run the project, it's only loading & loading the UI
![image](https://user-images.githubusercontent.com/60693492/184501757-38f0da78-299d-423e-b20d-7ca9a02fc683.png)
@ashik5757 please help me

**Comment by ashik5757** [comment]
Did you put all the files(png,txt) of *data* folder properly?

**Comment by TawhidGias** [comment]
Yes @ashik5757 I have put the data folder in src of the project

**Comment by ashik5757** [comment]
Open this project file in IntelliJ directly and then update sdk(if not
found), remove javafx-sdk that added and add your javafx-sdk again, add all
the module dependency (controlfx, mysql)

and then must change the directory path for javafx-sdk-16\lib in VM option
in Run Configurations as same procedure mention in Readme.me

Let me know whether it is working or not.

**Comment by ashik5757** [comment]
Check email, I attached a scoreboard.zip file

**Comment by TawhidGias** [comment]
I didn't get the file in my email. Can you send it again please @ashik5757?

**Comment by TawhidGias** [comment]
@ashik5757 Please help me quickly. Can we get a session in AnyDesk or TeamViewer? I need your help badly

**Comment by ashik5757** [comment]
Check the new released section,  I attached a zip file for IDE. And follow
the procedure mentioned in the previous email.

**Comment by ashik5757** [comment]
Let me know, whether it is working or not.

**Comment by TawhidGias** [comment]
@ashik5757 How can I remove the added javafx-sdk & add all module dependencies?

**Comment by TawhidGias** [comment]
@ashik5757 It's not working yet. Please help me
